// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dltvxwxormfvofwqcrqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsdHZ4d3hvcm1mdm9md3FjcnFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU1NDUxMDQsImV4cCI6MjA5MTEyMTEwNH0.fVC72Tub-qi1Iz064e0gytZR39uqjO1G7lcXpRIo6Tc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});